### ISSUE TITLE
Loading...

### ISSUE THREAD

**Issue by hermanjustinm** [Shreshth-mehra/Obsidian-TV-Tracker#1]
Stuck on "Loading..." on launch.

Occurs with and without setting arguments applied

> react.development.js:209 Warning: Failed prop type: The prop `xs` of `Grid` can only be used together with the `item` prop.
>     at Grid2 (plugin:tv-tracker:39666:22)
>     at MovieGrid (plugin:tv-tracker:40576:20)
>     at div
>     at eval (plugin:tv-tracker:26017:49)
>     at Container3 (plugin:tv-tracker:34667:23)
>     at ReactView (plugin:tv-tracker:89527:20)

printWarning @ react.development.js:209

**Comment by Shreshth-mehra** [comment]
Thank you for bringing this up. I have identified the issue and is currently under work. 

Quick fix - I have uploaded a folder called Template library to the github repo. Copy paste 1 or more files from this folder to the folder in your vault (This should be the same folder you have specified in the settings, please ensure this folder exists). Once you do this the plugin should load as expected. After you have added at least 1 movie/TV show of your choice using the add new button you can then remove this copy pasted file from the template library.

Bug explanation - Message you shared from the console is just a warning and is not causing this error. Instead, "Loading..." is shown when there are no movies to be displayed or are being currently loaded. As you can imagine, all new users will have their Movies folder empty and hence every new user should experience this issue. By adding any one movie/tv show title to the folder the app is allowed to load as expected.
