### ISSUE TITLE
[Feature Request] Episode Progress Tracking 

### ISSUE THREAD

**Issue by Airradda** [Shreshth-mehra/Obsidian-TV-Tracker#4]
It would be nice to be able to track the number of episodes watched relative to the total episodes in a series.

**Comment by Shreshth-mehra** [comment]
Hmm, that can be added easily. I'll look into it in the next release. I'm thinking I'll add a property to each Series for total number of episodes and a user input property for Episodes. Then you should be able to see a progress bar in the card for the show as a property. Is that something you had in mind or something else?

**Comment by Airradda** [comment]
Instead of a progress bar you could just have something as simple as `Ep. Seen: 33/96`.

I'm assuming "marking" episodes as watched would be done through editing the YAML or did you have plans for a "Edit" and/or "Details" view of some kind?

**Comment by Shreshth-mehra** [comment]
Makes sense. Yes, marking episodes would be done by editing the YAML. So "Series X" would have a YAML property for total number of episodes pulled from TMDB. And then there would be another YAML property where you enter the number for episodes seen. This property will have to changed manually to update the number of episodes seen

**Comment by Shreshth-mehra** [comment]
Have added this
